#cloud-config
users:
  - name: ubuntu
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM+iYb1iEOFDRXc/kYyt+kZKWMGLHqvBes1tdFv9qtL4 A@u-comp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash

package_update: true
package_upgrade: true
packages:
  - ansible
  - git

runcmd:
  # Настраиваем SSH
  - mkdir -p /home/ubuntu/.ssh
  - echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM+iYb1iEOFDRXc/kYyt+kZKWMGLHqvBes1tdFv9qtL4 A@u-comp" > /home/ubuntu/.ssh/authorized_keys
  - chmod 700 /home/ubuntu/.ssh
  - chmod 600 /home/ubuntu/.ssh/authorized_keys
  - chown -R ubuntu:ubuntu /home/ubuntu/.ssh
  
  # SSH сервер
  - sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -i 's/^#\?PubkeyAuthentication.*/PubkeyAuthentication yes/' /etc/ssh/sshd_config
  - systemctl restart sshd

  # Создаем директорию для Ansible
  - mkdir -p /home/ubuntu/Diplom/ansible
  - chown -R ubuntu:ubuntu /home/ubuntu/Diplom

  # Логирование
  - echo "Cloud-init completed at $(date)" > /var/log/cloud-init-completed.log
